# Site settings
title: Website of Alec Carpenter
email: alecgunnar@gmail.com
description: Personal website of Alec Carpenter.
baseurl: "/"
url: "http://www.alecgunnar.com"

# Build settings
markdown: kramdown


# SASS settings
sass:
    style: :compressed